services:
  - type: web
    name: zumar-law-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://zumar-e9y4azar9-zeeshans-projects-64a0dd2b.vercel.app/